version: '3.7'

services:
  app:
    image: ahovda/unifi:${UNIFI_VERSION}
    build:
      context: .
      args:
        version: ${UNIFI_VERSION}
    volumes:
      - data:/UniFi/data
    networks:
      - proxy
    environment:
      UNIFI_VERSION: 5.12.66
    ports:
      - 3478:3478/udp
    deploy:
      labels:
        - traefik.http.services.unifi_inform.loadbalancer.server.port=80
        - traefik.http.routers.unifi_inform.rule=Host("unifi.openit.com")
        - traefik.http.routers.unifi_inform.entrypoints=web
#        - traefik.tcp.routers.unifi_gui.rule=HostSNI("unifi.openit.com")
#        - traefik.tcp.routers.unifi_gui.entrypoints=web-secure
#        - traefik.tcp.routers.unifi_gui.tls.passthrough=true
#        - traefik.tcp.services.unifi_gui.loadbalancer.server.port=443
networks:
  proxy:
    external: true

volumes:
  data:
    external: true
    name: unifi_data
