version: '3.7'

services:
  app:
    image: ahovda/unifi:${UNIFI_VERSION}
    build:
      context: .
      args:
        version: ${UNIFI_VERSION}
    volumes:
      - data:/UniFi/data
    networks:
      - proxy
    environment:
      UNIFI_VERSION: 6.1.71
      INFORM_URL: unifi.domain.com
    ports:
      - 3478:3478/udp
    deploy:
      labels:
        - traefik.http.services.unifi_inform.loadbalancer.server.port=80
        - traefik.http.routers.unifi_inform.rule=Host("${INFORM_URL}")
        - traefik.http.routers.unifi_inform.entrypoints=web
networks:
  proxy:
    external: true

volumes:
  data:
    external: true
    name: unifi_data
